name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Test Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'tf/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy
        run: echo "Deploying application..."
