name: Test Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'tf/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run test
        run: echo "Running tests..."
